#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x3602B07F55D0C732 (gray@gnu.org)
#
Name     : cpio
Version  : 2.13
Release  : 31
URL      : https://mirrors.kernel.org/gnu/cpio/cpio-2.13.tar.gz
Source0  : https://mirrors.kernel.org/gnu/cpio/cpio-2.13.tar.gz
Source1  : https://mirrors.kernel.org/gnu/cpio/cpio-2.13.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0 GPL-3.0+
Requires: cpio-bin = %{version}-%{release}
Requires: cpio-info = %{version}-%{release}
Requires: cpio-license = %{version}-%{release}
Requires: cpio-locales = %{version}-%{release}
Requires: cpio-man = %{version}-%{release}
BuildRequires : bison
BuildRequires : glibc-locale
Patch1: backport-gcc10.patch

%description
This is the GNU cpio package
============================
* Introduction
==============

%package bin
Summary: bin components for the cpio package.
Group: Binaries
Requires: cpio-license = %{version}-%{release}

%description bin
bin components for the cpio package.


%package info
Summary: info components for the cpio package.
Group: Default

%description info
info components for the cpio package.


%package license
Summary: license components for the cpio package.
Group: Default

%description license
license components for the cpio package.


%package locales
Summary: locales components for the cpio package.
Group: Default

%description locales
locales components for the cpio package.


%package man
Summary: man components for the cpio package.
Group: Default

%description man
man components for the cpio package.


%prep
%setup -q -n cpio-2.13
cd %{_builddir}/cpio-2.13
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1589809473
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$FFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$FFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong -mzero-caller-saved-regs=used "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1589809473
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/cpio
cp %{_builddir}/cpio-2.13/COPYING %{buildroot}/usr/share/package-licenses/cpio/842745cb706f8f2126506f544492f7a80dbe29b3
%make_install
%find_lang cpio
## Remove excluded files
rm -f %{buildroot}/usr/libexec/rmt
rm -f %{buildroot}/usr/share/man/man8/rmt.8

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cpio

%files info
%defattr(0644,root,root,0755)
/usr/share/info/cpio.info

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cpio/842745cb706f8f2126506f544492f7a80dbe29b3

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/cpio.1

%files locales -f cpio.lang
%defattr(-,root,root,-)

