#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x3602B07F55D0C732 (gray@gnu.org)
#
Name     : cpio
Version  : 2.12
Release  : 25
URL      : http://mirrors.kernel.org/gnu/cpio/cpio-2.12.tar.bz2
Source0  : http://mirrors.kernel.org/gnu/cpio/cpio-2.12.tar.bz2
Source99 : http://mirrors.kernel.org/gnu/cpio/cpio-2.12.tar.bz2.sig
Summary  : A tool to copy files into or out of a cpio or tar archive
Group    : Development/Tools
License  : GPL-3.0 GPL-3.0+
Requires: cpio-bin = %{version}-%{release}
Requires: cpio-libexec = %{version}-%{release}
Requires: cpio-license = %{version}-%{release}
Requires: cpio-locales = %{version}-%{release}
Requires: cpio-man = %{version}-%{release}
BuildRequires : bison
BuildRequires : glibc-locale
Patch1: cve-2016-2037.patch

%description
This is the GNU cpio package
============================
* Introduction
==============

%package bin
Summary: bin components for the cpio package.
Group: Binaries
Requires: cpio-libexec = %{version}-%{release}
Requires: cpio-license = %{version}-%{release}

%description bin
bin components for the cpio package.


%package doc
Summary: doc components for the cpio package.
Group: Documentation
Requires: cpio-man = %{version}-%{release}

%description doc
doc components for the cpio package.


%package libexec
Summary: libexec components for the cpio package.
Group: Default
Requires: cpio-license = %{version}-%{release}

%description libexec
libexec components for the cpio package.


%package license
Summary: license components for the cpio package.
Group: Default

%description license
license components for the cpio package.


%package locales
Summary: locales components for the cpio package.
Group: Default

%description locales
locales components for the cpio package.


%package man
Summary: man components for the cpio package.
Group: Default

%description man
man components for the cpio package.


%prep
%setup -q -n cpio-2.12
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1557076289
export CFLAGS="$CFLAGS -fcf-protection=full -fno-lto -fstack-protector-strong "
export FCFLAGS="$CFLAGS -fcf-protection=full -fno-lto -fstack-protector-strong "
export FFLAGS="$CFLAGS -fcf-protection=full -fno-lto -fstack-protector-strong "
export CXXFLAGS="$CXXFLAGS -fcf-protection=full -fno-lto -fstack-protector-strong "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1557076289
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/cpio
cp COPYING %{buildroot}/usr/share/package-licenses/cpio/COPYING
%make_install
%find_lang cpio

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cpio

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/info/*

%files libexec
%defattr(-,root,root,-)
%exclude /usr/libexec/rmt

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cpio/COPYING

%files man
%defattr(0644,root,root,0755)
%exclude /usr/share/man/man8/rmt.8
/usr/share/man/man1/cpio.1

%files locales -f cpio.lang
%defattr(-,root,root,-)

